# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "/Jekyll_modern-blog" # the subpath of your site, e.g. /blog/
url: "https://amava-lin.github.io" # the base hostname & protocol for your site
